import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import { subDays, subMonths, subYears } from 'date-fns';

const prisma = new PrismaClient();

export async function seedDatabase() {
  // Create admin user
  const passwordHash = await bcrypt.hash('Demo@1234', 10);
  await prisma.user.create({
    data: {
      email: 'admin@isecnet.io',
      name: 'Mohammad Zubair',
      passwordHash,
      role: 'admin',
    },
  });

  const now = new Date();

  // 47 credentials across 5 sources
  const credentials = [
    // ── AWS IAM (20) ──────────────────────────────────────────────────────────
    {
      name: 'prod-rds-master-credential',
      type: 'SERVICE_ACCOUNT',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 95,
      riskLevel: 'CRITICAL',
      hasProductionAccess: true,
      isOverPrivileged: true,
      isShared: true,
      neverExpires: true,
      lastRotated: null,
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['rds:*', 'secretsmanager:*', 'kms:Decrypt', 'kms:Encrypt']),
      blastRadius: JSON.stringify(['Customer database (10M records)', 'Financial transaction history', 'PII data of 10M users', 'Healthcare records', '47 downstream services']),
    },
    {
      name: 'iam-full-admin-access-key',
      type: 'ACCESS_TOKEN',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 91,
      riskLevel: 'CRITICAL',
      hasProductionAccess: true,
      isOverPrivileged: true,
      isShared: false,
      neverExpires: true,
      lastRotated: null,
      lastUsed: subDays(now, 2),
      permissions: JSON.stringify(['iam:*', 'sts:*', 'organizations:*', 'sts:AssumeRole', 'iam:CreateUser', 'iam:AttachUserPolicy']),
      blastRadius: JSON.stringify(['Full AWS infrastructure control', 'Can create new admin accounts', 'Can revoke all credentials', 'Billing and cost management', 'All 200+ AWS services']),
    },
    {
      name: 'eks-cluster-admin-token',
      type: 'SERVICE_ACCOUNT',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 85,
      riskLevel: 'CRITICAL',
      hasProductionAccess: true,
      isOverPrivileged: true,
      isShared: false,
      neverExpires: true,
      lastRotated: null,
      lastUsed: subDays(now, 3),
      permissions: JSON.stringify(['eks:*', 'ec2:*', 'elasticloadbalancing:*']),
      blastRadius: JSON.stringify(['All Kubernetes workloads', 'Production containerized applications', 'Microservices fleet (34 services)', 'Internal network access']),
    },
    {
      name: 'prod-ec2-deploy-service-key',
      type: 'API_KEY',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 82,
      riskLevel: 'CRITICAL',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: true,
      neverExpires: true,
      lastRotated: subYears(now, 2),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['ec2:RunInstances', 'ec2:TerminateInstances', 'ec2:DescribeInstances', 's3:GetObject', 's3:PutObject']),
      blastRadius: JSON.stringify(['Production EC2 fleet (240 instances)', 'S3 production data buckets', 'Auto-scaling groups', 'Load balancer configuration']),
    },
    {
      name: 's3-production-backup-key',
      type: 'ACCESS_TOKEN',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 72,
      riskLevel: 'HIGH',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: true,
      neverExpires: true,
      lastRotated: subMonths(now, 8),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['s3:*']),
      blastRadius: JSON.stringify(['All S3 buckets (23 buckets)', 'Customer data backups', 'Application artifacts', 'Log archives']),
    },
    {
      name: 'cloudformation-infra-deploy-key',
      type: 'API_KEY',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 68,
      riskLevel: 'HIGH',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: false,
      lastRotated: subMonths(now, 6),
      lastUsed: subDays(now, 5),
      expiresAt: subDays(now, -30),
      permissions: JSON.stringify(['cloudformation:*', 'iam:PassRole', 'ec2:DescribeVpcs']),
      blastRadius: JSON.stringify(['Infrastructure as Code deployments', 'Production stack modifications', 'IAM role modifications']),
    },
    {
      name: 'redshift-analytics-service-key',
      type: 'DATABASE_CREDENTIAL',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 70,
      riskLevel: 'HIGH',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 14),
      lastUsed: subDays(now, 2),
      permissions: JSON.stringify(['redshift:GetClusterCredentials', 'redshift:DescribeClusters']),
      blastRadius: JSON.stringify(['Data warehouse (500TB)', 'Business analytics data', 'Customer behaviour data', 'Financial analytics']),
    },
    {
      name: 'ec2-autoscaling-service-account',
      type: 'SERVICE_ACCOUNT',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 65,
      riskLevel: 'HIGH',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 10),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['autoscaling:*', 'ec2:DescribeInstances', 'cloudwatch:PutMetricData']),
      blastRadius: JSON.stringify(['Auto-scaling group management', 'Production capacity control', 'CloudWatch metrics']),
    },
    {
      name: 'lambda-execution-role-key',
      type: 'SERVICE_ACCOUNT',
      source: 'aws',
      sourceDetail: 'AWS Staging (987654321098)',
      status: 'ACTIVE',
      riskScore: 55,
      riskLevel: 'MEDIUM',
      hasProductionAccess: false,
      isOverPrivileged: true,
      isShared: true,
      neverExpires: true,
      lastRotated: subMonths(now, 3),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['lambda:*', 's3:GetObject', 'dynamodb:*', 'sns:Publish', 'sqs:*', 'logs:*']),
      blastRadius: JSON.stringify(['12 Lambda functions', 'DynamoDB tables (staging)', 'SQS queues', 'SNS topics']),
    },
    {
      name: 'sqs-message-processor-key',
      type: 'API_KEY',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 45,
      riskLevel: 'MEDIUM',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: false,
      lastRotated: subMonths(now, 2),
      lastUsed: subDays(now, 1),
      expiresAt: subDays(now, -90),
      permissions: JSON.stringify(['sqs:ReceiveMessage', 'sqs:DeleteMessage', 'sqs:SendMessage']),
      blastRadius: JSON.stringify(['Order processing queue', 'Notification queue', 'Background job queue']),
    },
    {
      name: 'dynamodb-application-user',
      type: 'DATABASE_CREDENTIAL',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 52,
      riskLevel: 'MEDIUM',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 4),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['dynamodb:PutItem', 'dynamodb:GetItem', 'dynamodb:Query', 'dynamodb:Scan']),
      blastRadius: JSON.stringify(['User session data', 'Application state tables', 'Feature flag configurations']),
    },
    {
      name: 'codebuild-pipeline-service-key',
      type: 'SERVICE_ACCOUNT',
      source: 'aws',
      sourceDetail: 'AWS DevOps (555666777888)',
      status: 'ACTIVE',
      riskScore: 58,
      riskLevel: 'MEDIUM',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 5),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['codebuild:*', 's3:PutObject', 'ecr:*', 'logs:CreateLogGroup']),
      blastRadius: JSON.stringify(['CI/CD pipeline control', 'Docker image registry', 'Build artifacts']),
    },
    {
      name: 'route53-dns-management-key',
      type: 'API_KEY',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 48,
      riskLevel: 'MEDIUM',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 3),
      lastUsed: subDays(now, 7),
      permissions: JSON.stringify(['route53:ChangeResourceRecordSets', 'route53:ListHostedZones']),
      blastRadius: JSON.stringify(['DNS for all company domains', 'Customer-facing domain records', 'Internal service discovery']),
    },
    {
      name: 'elasticache-session-access',
      type: 'DATABASE_CREDENTIAL',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 42,
      riskLevel: 'MEDIUM',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 2),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['elasticache:DescribeCacheClusters', 'elasticache:Connect']),
      blastRadius: JSON.stringify(['User session cache', 'API rate limit data', 'Temporary application state']),
    },
    {
      name: 'ses-email-sender-key',
      type: 'API_KEY',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 35,
      riskLevel: 'LOW',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: false,
      lastRotated: subMonths(now, 1),
      lastUsed: subDays(now, 1),
      expiresAt: subDays(now, -180),
      permissions: JSON.stringify(['ses:SendEmail', 'ses:SendRawEmail']),
      blastRadius: JSON.stringify(['Email sending (up to 50,000/day)', 'Transactional email system']),
    },
    {
      name: 'sns-notification-service',
      type: 'SERVICE_ACCOUNT',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 28,
      riskLevel: 'LOW',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 1),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['sns:Publish', 'sns:ListTopics']),
      blastRadius: JSON.stringify(['Push notifications', 'SMS alerts (limited scope)']),
    },
    {
      name: 'waf-protection-management-key',
      type: 'API_KEY',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 30,
      riskLevel: 'LOW',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 1),
      lastUsed: subDays(now, 14),
      permissions: JSON.stringify(['wafv2:GetWebACL', 'wafv2:UpdateWebACL', 'wafv2:ListWebACLs']),
      blastRadius: JSON.stringify(['Web Application Firewall rules', 'IP block/allow lists']),
    },
    {
      name: 'cloudwatch-monitoring-key',
      type: 'API_KEY',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ORPHANED',
      riskScore: 22,
      riskLevel: 'LOW',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 2),
      lastUsed: subDays(now, 120),
      permissions: JSON.stringify(['cloudwatch:GetMetricData', 'cloudwatch:ListMetrics', 'logs:GetLogEvents']),
      blastRadius: JSON.stringify(['Monitoring dashboards', 'Log data (read-only)']),
    },
    {
      name: 'glacier-archive-access-key',
      type: 'ACCESS_TOKEN',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 15,
      riskLevel: 'MINIMAL',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: false,
      lastRotated: subMonths(now, 1),
      lastUsed: subDays(now, 30),
      expiresAt: subDays(now, -365),
      permissions: JSON.stringify(['glacier:GetJobOutput', 'glacier:InitiateJob']),
      blastRadius: JSON.stringify(['Cold storage archives (read-only)', 'Compliance document archives']),
    },
    {
      name: 'secrets-manager-rotation-key',
      type: 'SERVICE_ACCOUNT',
      source: 'aws',
      sourceDetail: 'AWS Production (123456789012)',
      status: 'ACTIVE',
      riskScore: 32,
      riskLevel: 'LOW',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 1),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['secretsmanager:RotateSecret', 'secretsmanager:GetSecretValue']),
      blastRadius: JSON.stringify(['Secrets rotation automation', 'Limited secrets access']),
    },

    // ── GitHub Actions (8) ────────────────────────────────────────────────────
    {
      name: 'github-org-admin-token',
      type: 'OAUTH_TOKEN',
      source: 'github',
      sourceDetail: 'GitHub Org: isecnet-solutions',
      status: 'ACTIVE',
      riskScore: 82,
      riskLevel: 'CRITICAL',
      hasProductionAccess: true,
      isOverPrivileged: true,
      isShared: false,
      neverExpires: true,
      lastRotated: null,
      lastUsed: subDays(now, 2),
      permissions: JSON.stringify(['admin:org', 'repo', 'delete_repo', 'admin:org_hook', 'write:packages']),
      blastRadius: JSON.stringify(['All organisation repositories', 'GitHub Actions secrets', 'Webhook configurations', 'Package registry', 'Branch protection bypass']),
    },
    {
      name: 'github-actions-prod-deploy-token',
      type: 'ACCESS_TOKEN',
      source: 'github',
      sourceDetail: 'GitHub Org: isecnet-solutions',
      status: 'ACTIVE',
      riskScore: 75,
      riskLevel: 'HIGH',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 11),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['repo', 'write:packages', 'read:org']),
      blastRadius: JSON.stringify(['Production deployment pipelines', 'Container registry write access', 'All repositories (read/write)']),
    },
    {
      name: 'github-pat-backend-service',
      type: 'ACCESS_TOKEN',
      source: 'github',
      sourceDetail: 'GitHub Org: isecnet-solutions',
      status: 'ACTIVE',
      riskScore: 62,
      riskLevel: 'HIGH',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 7),
      lastUsed: subDays(now, 3),
      permissions: JSON.stringify(['repo', 'read:org', 'gist']),
      blastRadius: JSON.stringify(['Source code (all repos)', 'GitHub Gists', 'Repository secrets read']),
    },
    {
      name: 'github-release-automation-token',
      type: 'ACCESS_TOKEN',
      source: 'github',
      sourceDetail: 'GitHub Org: isecnet-solutions',
      status: 'ACTIVE',
      riskScore: 56,
      riskLevel: 'MEDIUM',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: false,
      lastRotated: subMonths(now, 4),
      lastUsed: subDays(now, 7),
      expiresAt: subDays(now, -60),
      permissions: JSON.stringify(['repo', 'write:packages']),
      blastRadius: JSON.stringify(['Release tag creation', 'Package publishing', 'Release notes generation']),
    },
    {
      name: 'github-ci-test-runner-account',
      type: 'SERVICE_ACCOUNT',
      source: 'github',
      sourceDetail: 'GitHub Org: isecnet-solutions',
      status: 'ACTIVE',
      riskScore: 50,
      riskLevel: 'MEDIUM',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: true,
      neverExpires: true,
      lastRotated: subMonths(now, 3),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['repo:status', 'read:org', 'actions:read']),
      blastRadius: JSON.stringify(['CI pipeline status', 'Test result access', 'GitHub Actions read access']),
    },
    {
      name: 'github-webhook-secret-key',
      type: 'SECRET_KEY',
      source: 'github',
      sourceDetail: 'GitHub Org: isecnet-solutions',
      status: 'ACTIVE',
      riskScore: 44,
      riskLevel: 'MEDIUM',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 6),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['webhook:receive', 'webhook:verify']),
      blastRadius: JSON.stringify(['Webhook payload verification', 'GitHub event processing']),
    },
    {
      name: 'github-packages-read-token',
      type: 'ACCESS_TOKEN',
      source: 'github',
      sourceDetail: 'GitHub Org: isecnet-solutions',
      status: 'ACTIVE',
      riskScore: 38,
      riskLevel: 'LOW',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: false,
      lastRotated: subMonths(now, 2),
      lastUsed: subDays(now, 2),
      expiresAt: subDays(now, -120),
      permissions: JSON.stringify(['read:packages', 'read:org']),
      blastRadius: JSON.stringify(['Package registry read (internal packages only)']),
    },
    {
      name: 'github-security-scanner-token',
      type: 'ACCESS_TOKEN',
      source: 'github',
      sourceDetail: 'GitHub Org: isecnet-solutions',
      status: 'ACTIVE',
      riskScore: 25,
      riskLevel: 'LOW',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: false,
      lastRotated: subMonths(now, 1),
      lastUsed: subDays(now, 1),
      expiresAt: subDays(now, -90),
      permissions: JSON.stringify(['security_events:read', 'repo:status']),
      blastRadius: JSON.stringify(['Security alert read access', 'Code scanning results']),
    },

    // ── Kubernetes (6) ────────────────────────────────────────────────────────
    {
      name: 'k8s-prod-cluster-admin-token',
      type: 'SERVICE_ACCOUNT',
      source: 'kubernetes',
      sourceDetail: 'K8s Cluster: prod-us-east-1',
      status: 'ACTIVE',
      riskScore: 87,
      riskLevel: 'CRITICAL',
      hasProductionAccess: true,
      isOverPrivileged: true,
      isShared: false,
      neverExpires: true,
      lastRotated: null,
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['cluster-admin', 'get/list/watch/create/update/delete all resources']),
      blastRadius: JSON.stringify(['All Kubernetes namespaces', 'All running pods (340 pods)', 'Secrets and ConfigMaps', 'Node access', 'Network policies']),
    },
    {
      name: 'k8s-staging-deployment-token',
      type: 'SERVICE_ACCOUNT',
      source: 'kubernetes',
      sourceDetail: 'K8s Cluster: staging-us-east-1',
      status: 'ACTIVE',
      riskScore: 63,
      riskLevel: 'HIGH',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 9),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['deployments:create/update/delete', 'pods:get/list', 'services:get/list']),
      blastRadius: JSON.stringify(['Staging environment deployments', 'All staging namespaces', 'Staging service mesh']),
    },
    {
      name: 'k8s-vault-injector-account',
      type: 'SERVICE_ACCOUNT',
      source: 'kubernetes',
      sourceDetail: 'K8s Cluster: prod-us-east-1',
      status: 'ACTIVE',
      riskScore: 67,
      riskLevel: 'HIGH',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 8),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['vault:read_secrets', 'k8s:inject_env', 'mutatingwebhook:*']),
      blastRadius: JSON.stringify(['All vault secrets injection', 'Environment variable injection into all pods', 'Secrets management plane']),
    },
    {
      name: 'k8s-monitoring-prometheus-token',
      type: 'SERVICE_ACCOUNT',
      source: 'kubernetes',
      sourceDetail: 'K8s Cluster: prod-us-east-1',
      status: 'ACTIVE',
      riskScore: 48,
      riskLevel: 'MEDIUM',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 4),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['pods:get/list/watch', 'services:get/list', 'endpoints:get/list']),
      blastRadius: JSON.stringify(['Metrics scraping from all pods', 'Service endpoint discovery']),
    },
    {
      name: 'k8s-ingress-controller-account',
      type: 'SERVICE_ACCOUNT',
      source: 'kubernetes',
      sourceDetail: 'K8s Cluster: prod-us-east-1',
      status: 'ACTIVE',
      riskScore: 42,
      riskLevel: 'MEDIUM',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 3),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['ingresses:get/list/watch/update', 'services:get/list', 'configmaps:get/create/update']),
      blastRadius: JSON.stringify(['Traffic routing for all services', 'TLS certificate management', 'Ingress rule control']),
    },
    {
      name: 'k8s-cert-manager-key',
      type: 'SERVICE_ACCOUNT',
      source: 'kubernetes',
      sourceDetail: 'K8s Cluster: prod-us-east-1',
      status: 'ACTIVE',
      riskScore: 28,
      riskLevel: 'LOW',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 2),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['certificates:get/list/create/update', 'secrets:get/create/update']),
      blastRadius: JSON.stringify(['TLS certificate issuance', 'Certificate renewal automation']),
    },

    // ── SaaS Integrations (8) ─────────────────────────────────────────────────
    {
      name: 'stripe-production-webhook-secret',
      type: 'SECRET_KEY',
      source: 'saas',
      sourceDetail: 'Stripe (Live Mode)',
      status: 'ACTIVE',
      riskScore: 73,
      riskLevel: 'HIGH',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subDays(now, 890),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['payment:process', 'subscription:manage', 'refund:create', 'customer:read']),
      blastRadius: JSON.stringify(['Payment processing pipeline', 'Subscription management', 'Customer billing data', 'Refund initiation']),
    },
    {
      name: 'salesforce-crm-api-key',
      type: 'API_KEY',
      source: 'saas',
      sourceDetail: 'Salesforce (Production Org)',
      status: 'ACTIVE',
      riskScore: 55,
      riskLevel: 'MEDIUM',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 5),
      lastUsed: subDays(now, 2),
      permissions: JSON.stringify(['Account:read/write', 'Contact:read/write', 'Opportunity:read/write', 'Lead:read/write']),
      blastRadius: JSON.stringify(['Customer CRM data', 'Sales pipeline data', 'Lead/opportunity management']),
    },
    {
      name: 'slack-security-bot-token',
      type: 'OAUTH_TOKEN',
      source: 'saas',
      sourceDetail: 'Slack Workspace: isecnet',
      status: 'ACTIVE',
      riskScore: 32,
      riskLevel: 'LOW',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 2),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['chat:write', 'channels:read', 'users:read', 'files:read']),
      blastRadius: JSON.stringify(['Slack channel access', 'Message posting capability', 'User directory read']),
    },
    {
      name: 'hubspot-marketing-api-key',
      type: 'API_KEY',
      source: 'saas',
      sourceDetail: 'HubSpot (Production Portal)',
      status: 'ACTIVE',
      riskScore: 35,
      riskLevel: 'LOW',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 2),
      lastUsed: subDays(now, 3),
      permissions: JSON.stringify(['contacts:read/write', 'deals:read', 'email:send', 'forms:submit']),
      blastRadius: JSON.stringify(['Marketing contact list', 'Email campaign management', 'Deal pipeline read']),
    },
    {
      name: 'twilio-sms-auth-token',
      type: 'SECRET_KEY',
      source: 'saas',
      sourceDetail: 'Twilio (Production Account)',
      status: 'ACTIVE',
      riskScore: 48,
      riskLevel: 'MEDIUM',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 6),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['sms:send', 'voice:call', 'verify:create', 'lookup:read']),
      blastRadius: JSON.stringify(['SMS sending (all customers)', 'Voice call initiation', 'Phone number verification']),
    },
    {
      name: 'sendgrid-transactional-api-key',
      type: 'API_KEY',
      source: 'saas',
      sourceDetail: 'SendGrid (Production)',
      status: 'ACTIVE',
      riskScore: 28,
      riskLevel: 'LOW',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: false,
      lastRotated: subMonths(now, 1),
      lastUsed: subDays(now, 1),
      expiresAt: subDays(now, -180),
      permissions: JSON.stringify(['mail.send', 'stats.read', 'suppressions.read']),
      blastRadius: JSON.stringify(['Transactional email sending', 'Email delivery statistics']),
    },
    {
      name: 'datadog-monitoring-api-key',
      type: 'API_KEY',
      source: 'saas',
      sourceDetail: 'Datadog (Production Org)',
      status: 'ACTIVE',
      riskScore: 45,
      riskLevel: 'MEDIUM',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: true,
      neverExpires: true,
      lastRotated: subMonths(now, 5),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['metrics:write', 'events:write', 'logs:write', 'dashboards:read']),
      blastRadius: JSON.stringify(['APM data ingestion', 'Infrastructure metrics', 'Log aggregation', 'Alert configuration']),
    },
    {
      name: 'pagerduty-incident-key',
      type: 'API_KEY',
      source: 'saas',
      sourceDetail: 'PagerDuty (Production Account)',
      status: 'ACTIVE',
      riskScore: 22,
      riskLevel: 'LOW',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: false,
      lastRotated: subMonths(now, 1),
      lastUsed: subDays(now, 2),
      expiresAt: subDays(now, -365),
      permissions: JSON.stringify(['incidents:create', 'services:read', 'escalation_policies:read']),
      blastRadius: JSON.stringify(['Incident creation', 'On-call routing (read-only)']),
    },

    // ── AI Agent Keys (5) ─────────────────────────────────────────────────────
    {
      name: 'openai-production-api-key',
      type: 'AI_AGENT_KEY',
      source: 'ai-agent',
      sourceDetail: 'OpenAI (Production Org)',
      status: 'ACTIVE',
      riskScore: 83,
      riskLevel: 'CRITICAL',
      hasProductionAccess: true,
      isOverPrivileged: true,
      isShared: true,
      neverExpires: true,
      lastRotated: null,
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['gpt-4:invoke', 'dall-e:generate', 'embeddings:create', 'fine-tuning:create', 'files:upload']),
      blastRadius: JSON.stringify(['Unlimited GPT-4 API calls ($$$)', 'Fine-tuning with company data', 'File storage with sensitive data', 'Used by 12 microservices simultaneously']),
    },
    {
      name: 'anthropic-claude-research-key',
      type: 'AI_AGENT_KEY',
      source: 'ai-agent',
      sourceDetail: 'Anthropic (Research Account)',
      status: 'ACTIVE',
      riskScore: 68,
      riskLevel: 'HIGH',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 9),
      lastUsed: subDays(now, 1),
      permissions: JSON.stringify(['claude-3-opus:invoke', 'claude-3-sonnet:invoke', 'batch:create']),
      blastRadius: JSON.stringify(['LLM API consumption', 'Batch inference jobs', 'Sensitive document analysis']),
    },
    {
      name: 'langchain-orchestration-key',
      type: 'AI_AGENT_KEY',
      source: 'ai-agent',
      sourceDetail: 'LangSmith (Production)',
      status: 'ACTIVE',
      riskScore: 52,
      riskLevel: 'MEDIUM',
      hasProductionAccess: true,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 4),
      lastUsed: subDays(now, 2),
      permissions: JSON.stringify(['runs:create', 'traces:read/write', 'datasets:read', 'feedback:create']),
      blastRadius: JSON.stringify(['Agent execution traces', 'LLM chain orchestration', 'Prompt template access']),
    },
    {
      name: 'custom-agent-alpha-service-token',
      type: 'AI_AGENT_KEY',
      source: 'ai-agent',
      sourceDetail: 'Internal AI Platform',
      status: 'ACTIVE',
      riskScore: 44,
      riskLevel: 'MEDIUM',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: true,
      lastRotated: subMonths(now, 3),
      lastUsed: subDays(now, 3),
      permissions: JSON.stringify(['agent:execute', 'tools:invoke', 'memory:read/write']),
      blastRadius: JSON.stringify(['Internal agent execution', 'Tool invocation (sandboxed)', 'Agent memory store']),
    },
    {
      name: 'custom-agent-beta-token',
      type: 'AI_AGENT_KEY',
      source: 'ai-agent',
      sourceDetail: 'Internal AI Platform',
      status: 'ACTIVE',
      riskScore: 35,
      riskLevel: 'LOW',
      hasProductionAccess: false,
      isOverPrivileged: false,
      isShared: false,
      neverExpires: false,
      lastRotated: subMonths(now, 1),
      lastUsed: subDays(now, 5),
      expiresAt: subDays(now, -120),
      permissions: JSON.stringify(['agent:execute', 'tools:invoke']),
      blastRadius: JSON.stringify(['Beta agent execution (limited tools)']),
    },
  ];

  const createdCreds: { id: string; name: string; riskScore: number }[] = [];
  for (const cred of credentials) {
    const c = await prisma.credential.create({ data: cred as any });
    createdCreds.push({ id: c.id, name: c.name, riskScore: c.riskScore });
  }

  // Map credential IDs by name
  const credMap: Record<string, string> = {};
  createdCreds.forEach((c) => { credMap[c.name] = c.id; });

  // 18 realistic alerts
  const alerts = [
    // CRITICAL (2)
    {
      title: 'Impossible Travel Detected',
      description: 'The credential "prod-ec2-deploy-service-key" was used from India (Mumbai) and United States (Virginia) within a 4-minute window — physically impossible without credential theft.',
      severity: 'CRITICAL',
      type: 'IMPOSSIBLE_TRAVEL',
      status: 'OPEN',
      credentialId: credMap['prod-ec2-deploy-service-key'],
      credentialName: 'prod-ec2-deploy-service-key',
      detectedAt: subDays(now, 1),
    },
    {
      title: 'Production Credential Exposed in GitHub History',
      description: 'The "prod-rds-master-credential" service account credentials were found in a git commit from 14 months ago in the backend-api repository. The commit was deleted but the history may still be accessible.',
      severity: 'CRITICAL',
      type: 'EXPOSED_IN_CODE',
      status: 'OPEN',
      credentialId: credMap['prod-rds-master-credential'],
      credentialName: 'prod-rds-master-credential',
      detectedAt: subDays(now, 2),
    },
    // HIGH (4)
    {
      title: 'IAM Admin Key Privilege Escalation Attempt',
      description: 'The "iam-full-admin-access-key" attempted to create a new IAM user with AdministratorAccess policy attached. This action was blocked by SCP but indicates potential compromise or misuse.',
      severity: 'HIGH',
      type: 'PRIVILEGE_ESCALATION',
      status: 'OPEN',
      credentialId: credMap['iam-full-admin-access-key'],
      credentialName: 'iam-full-admin-access-key',
      detectedAt: subDays(now, 3),
    },
    {
      title: 'OpenAI Key — Anomalous API Call Volume',
      description: 'The "openai-production-api-key" made 52,847 API calls in a single hour (normal: ~200/hour). Possible data exfiltration via LLM prompt injection or unauthorized batch job.',
      severity: 'HIGH',
      type: 'ANOMALOUS_USAGE',
      status: 'OPEN',
      credentialId: credMap['openai-production-api-key'],
      credentialName: 'openai-production-api-key',
      detectedAt: subDays(now, 1),
    },
    {
      title: 'Kubernetes Cluster-Admin Token on Production',
      description: 'The "k8s-prod-cluster-admin-token" has cluster-admin ClusterRoleBinding — full unrestricted access to all Kubernetes resources. This violates least-privilege policy and has never been rotated.',
      severity: 'HIGH',
      type: 'OVER_PRIVILEGED',
      status: 'ACKNOWLEDGED',
      credentialId: credMap['k8s-prod-cluster-admin-token'],
      credentialName: 'k8s-prod-cluster-admin-token',
      detectedAt: subDays(now, 5),
    },
    {
      title: 'Stripe Webhook Secret — 890 Days Without Rotation',
      description: 'The "stripe-production-webhook-secret" has not been rotated in 890 days (2.4 years). PCI DSS v4.0 requires rotation every 90 days for payment credentials. Compliance violation.',
      severity: 'HIGH',
      type: 'NEVER_ROTATED',
      status: 'OPEN',
      credentialId: credMap['stripe-production-webhook-secret'],
      credentialName: 'stripe-production-webhook-secret',
      detectedAt: subDays(now, 4),
    },
    // MEDIUM (6)
    {
      title: 'Service Account Unused for 120+ Days',
      description: 'The "cloudwatch-monitoring-key" has not been used in 120 days. This is likely an orphaned credential from a decommissioned monitoring agent. Recommend deletion.',
      severity: 'MEDIUM',
      type: 'ANOMALOUS_USAGE',
      status: 'OPEN',
      credentialId: credMap['cloudwatch-monitoring-key'],
      credentialName: 'cloudwatch-monitoring-key',
      detectedAt: subDays(now, 6),
    },
    {
      title: 'GitHub Actions Deploy Token Approaching Expiry',
      description: 'The "github-actions-prod-deploy-token" expires in 14 days. Expiry without rotation will break all CI/CD deployment pipelines to production.',
      severity: 'MEDIUM',
      type: 'EXPIRED_CREDENTIAL',
      status: 'OPEN',
      credentialId: credMap['github-actions-prod-deploy-token'],
      credentialName: 'github-actions-prod-deploy-token',
      detectedAt: subDays(now, 7),
    },
    {
      title: 'Lambda Execution Role — Over-Privileged',
      description: 'The "lambda-execution-role-key" has DynamoDB full access (dynamodb:*) but the function only needs PutItem and GetItem. The excess permissions increase blast radius by 340%.',
      severity: 'MEDIUM',
      type: 'OVER_PRIVILEGED',
      status: 'OPEN',
      credentialId: credMap['lambda-execution-role-key'],
      credentialName: 'lambda-execution-role-key',
      detectedAt: subDays(now, 8),
    },
    {
      title: 'Shared Credential Detected Across 4 Systems',
      description: 'The "s3-production-backup-key" is being used by 4 different services simultaneously. If compromised, all 4 systems are at risk and rotation will require coordinated downtime.',
      severity: 'MEDIUM',
      type: 'ANOMALOUS_USAGE',
      status: 'OPEN',
      credentialId: credMap['s3-production-backup-key'],
      credentialName: 's3-production-backup-key',
      detectedAt: subDays(now, 9),
    },
    {
      title: 'GitHub PAT with Excessive Scope',
      description: 'The "github-pat-backend-service" has "gist" and "delete_repo" implicit access via full "repo" scope. The service only requires read access to 2 specific repositories.',
      severity: 'MEDIUM',
      type: 'OVER_PRIVILEGED',
      status: 'ACKNOWLEDGED',
      credentialId: credMap['github-pat-backend-service'],
      credentialName: 'github-pat-backend-service',
      detectedAt: subDays(now, 10),
    },
    {
      title: 'Geographic Access Anomaly',
      description: 'The "redshift-analytics-service-key" was accessed from an IP address geolocated to Eastern Europe (Romania). This key has never previously been used outside of AWS us-east-1 region.',
      severity: 'MEDIUM',
      type: 'GEOGRAPHIC_ANOMALY',
      status: 'OPEN',
      credentialId: credMap['redshift-analytics-service-key'],
      credentialName: 'redshift-analytics-service-key',
      detectedAt: subDays(now, 11),
    },
    // LOW (4)
    {
      title: 'Credential Created Without Owner Assignment',
      description: 'The "elasticache-session-access" credential was created 4 months ago with no owner assigned. If the creating employee leaves, this becomes a permanently orphaned credential.',
      severity: 'LOW',
      type: 'ANOMALOUS_USAGE',
      status: 'OPEN',
      credentialId: credMap['elasticache-session-access'],
      credentialName: 'elasticache-session-access',
      detectedAt: subDays(now, 12),
    },
    {
      title: 'Rotation Schedule Not Configured',
      description: 'The "slack-security-bot-token" has no automatic rotation schedule set. Manual rotation dependency creates risk of indefinite credential age.',
      severity: 'LOW',
      type: 'NEVER_ROTATED',
      status: 'OPEN',
      credentialId: credMap['slack-security-bot-token'],
      credentialName: 'slack-security-bot-token',
      detectedAt: subDays(now, 13),
    },
    {
      title: 'Twilio Auth Token — Rotation Overdue',
      description: 'The "twilio-sms-auth-token" was last rotated 6 months ago. Twilio recommends rotation every 90 days for production accounts. Currently 90 days past recommended rotation date.',
      severity: 'LOW',
      type: 'NEVER_ROTATED',
      status: 'RESOLVED',
      credentialId: credMap['twilio-sms-auth-token'],
      credentialName: 'twilio-sms-auth-token',
      detectedAt: subDays(now, 14),
      resolvedAt: subDays(now, 3),
    },
    {
      title: 'Salesforce API — MFA Not Enforced',
      description: 'The "salesforce-crm-api-key" connected integration user account does not have MFA enforced at the Salesforce level. Salesforce now mandates MFA for all API integrations.',
      severity: 'LOW',
      type: 'OVER_PRIVILEGED',
      status: 'OPEN',
      credentialId: credMap['salesforce-crm-api-key'],
      credentialName: 'salesforce-crm-api-key',
      detectedAt: subDays(now, 15),
    },
    // INFO (2)
    {
      title: 'Credential Rotation Completed Successfully',
      description: 'The "ses-email-sender-key" was successfully rotated. Risk score reduced from 68 to 35. All systems using this credential have been automatically updated with the new value.',
      severity: 'INFO',
      type: 'ANOMALOUS_USAGE',
      status: 'RESOLVED',
      credentialId: credMap['ses-email-sender-key'],
      credentialName: 'ses-email-sender-key',
      detectedAt: subDays(now, 16),
      resolvedAt: subDays(now, 16),
    },
    {
      title: 'New AI Agent Credential Discovered',
      description: 'A new credential "custom-agent-beta-token" was discovered during the scheduled scan. The credential has been automatically classified as AI_AGENT_KEY and assigned a risk score of 35.',
      severity: 'INFO',
      type: 'ANOMALOUS_USAGE',
      status: 'RESOLVED',
      credentialId: credMap['custom-agent-beta-token'],
      credentialName: 'custom-agent-beta-token',
      detectedAt: subDays(now, 17),
      resolvedAt: subDays(now, 17),
    },
  ];

  for (const alert of alerts) {
    await prisma.alert.create({ data: alert as any });
  }

  // 12 rotation history records
  const rotations = [
    { credentialId: credMap['ses-email-sender-key'], credentialName: 'ses-email-sender-key', rotatedAt: subDays(now, 30), previousRisk: 68, newRisk: 35, status: 'SUCCESS', notes: 'Scheduled rotation — SES key policy compliance' },
    { credentialId: credMap['sns-notification-service'], credentialName: 'sns-notification-service', rotatedAt: subDays(now, 32), previousRisk: 55, newRisk: 28, status: 'SUCCESS', notes: 'Quarterly rotation cycle' },
    { credentialId: credMap['sendgrid-transactional-api-key'], credentialName: 'sendgrid-transactional-api-key', rotatedAt: subMonths(now, 1).valueOf() ? subMonths(now, 1) : subDays(now, 30), previousRisk: 45, newRisk: 28, status: 'SUCCESS', notes: 'Auto-rotation triggered' },
    { credentialId: credMap['github-security-scanner-token'], credentialName: 'github-security-scanner-token', rotatedAt: subDays(now, 45), previousRisk: 42, newRisk: 25, status: 'SUCCESS', notes: 'Routine rotation — 90 day policy' },
    { credentialId: credMap['pagerduty-incident-key'], credentialName: 'pagerduty-incident-key', rotatedAt: subDays(now, 50), previousRisk: 38, newRisk: 22, status: 'SUCCESS', notes: 'Annual rotation' },
    { credentialId: credMap['k8s-cert-manager-key'], credentialName: 'k8s-cert-manager-key', rotatedAt: subMonths(now, 2), previousRisk: 45, newRisk: 28, status: 'SUCCESS', notes: 'K8s service account rotation' },
    { credentialId: credMap['waf-protection-management-key'], credentialName: 'waf-protection-management-key', rotatedAt: subMonths(now, 1), previousRisk: 48, newRisk: 30, status: 'SUCCESS', notes: 'Security team rotation' },
    { credentialId: credMap['sqs-message-processor-key'], credentialName: 'sqs-message-processor-key', rotatedAt: subMonths(now, 2), previousRisk: 62, newRisk: 45, status: 'SUCCESS', notes: 'Infrastructure security audit' },
    { credentialId: credMap['cloudwatch-monitoring-key'], credentialName: 'cloudwatch-monitoring-key', rotatedAt: subMonths(now, 2), previousRisk: 35, newRisk: 22, status: 'SUCCESS', notes: 'Monitoring team rotation' },
    { credentialId: credMap['glacier-archive-access-key'], credentialName: 'glacier-archive-access-key', rotatedAt: subMonths(now, 1), previousRisk: 25, newRisk: 15, status: 'SUCCESS', notes: 'Cold storage credential update' },
    { credentialId: credMap['github-packages-read-token'], credentialName: 'github-packages-read-token', rotatedAt: subMonths(now, 2), previousRisk: 52, newRisk: 38, status: 'SUCCESS', notes: 'Package registry access rotation' },
    { credentialId: credMap['lambda-execution-role-key'], credentialName: 'lambda-execution-role-key', rotatedAt: subMonths(now, 3), previousRisk: 72, newRisk: 55, status: 'SUCCESS', notes: 'Lambda role permission review' },
  ];

  for (const rotation of rotations) {
    await prisma.rotationHistory.create({ data: rotation as any });
  }

  // Create an initial demo scan job
  await prisma.scanJob.create({
    data: {
      status: 'COMPLETED',
      source: 'demo',
      startedAt: subDays(now, 1),
      completedAt: subDays(now, 1),
      credentialsFound: 47,
      issuesFound: 18,
      logs: JSON.stringify([
        '[10:00:01] Connecting to AWS IAM...',
        '[10:00:03] Connected successfully',
        '[10:00:05] Scanning IAM users... found 20 credentials',
        '[10:00:08] Scanning GitHub organisation... found 8 tokens',
        '[10:00:11] Scanning Kubernetes clusters... found 6 service accounts',
        '[10:00:14] Scanning SaaS integrations... found 8 API keys',
        '[10:00:16] Scanning AI agent credentials... found 5 keys',
        '[10:00:18] Running risk scoring engine...',
        '[10:00:20] Generated 18 security alerts',
        '[10:00:21] Scan complete — 47 credentials found, 18 issues detected',
      ]),
    },
  });
}
